default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: iLent_development

test:
  <<: *default
  database: iLent_test

production:
  <<: *default
  database: iLent_production
  username: iLent
  password: <%= ENV['ILENT_DATABASE_PASSWORD'] %>
